import { PathPilotAPI } from "../lib/controller-client.js";
import { ConvAIClient } from "../lib/convai-client.js";
const $=id=>document.getElementById(id); const views={teach:$("teach-view"),run:$("run-view"),live:$("live-view")};
const beginTeaching=$("begin-teaching"),teachChat=$("teach-chat"),teachTyped=$("teach-typed"),teachTalk=$("teach-talk");
function teachBubble(text){const d=document.createElement("div");d.className="bubble";d.textContent=text;teachChat.append(d);teachChat.scrollTop=teachChat.scrollHeight;}
let tab=null,site=null,workflow=null,sessionId=null,since=0,rec=null,chunks=[],stream=null,recording=false,convai=null;
function show(name){Object.entries(views).forEach(([k,v])=>v.classList.toggle("hidden",k!==name));}
function bubble(text,type="narration"){const d=document.createElement("div");d.className=`bubble ${type}`;d.textContent=text;$("chat").append(d);$("chat").scrollTop=$("chat").scrollHeight;}
function friendly(host){if(/(^|\.)flytbase\.com$/i.test(host))return "FlytBase";return host.split(".").map(x=>x[0]?.toUpperCase()+x.slice(1)).join(" ");}
async function active(){return new Promise(r=>chrome.runtime.sendMessage({type:"PATHPILOT_GET_ACTIVE_TAB"},r));}
async function connect(){try{const ok=await PathPilotAPI.checkConnection();$("connection").textContent=ok?"Ready":"Not connected";$("connection").className=`status ${ok?"":"off"}`;$("connect").classList.toggle("hidden",ok);return ok}catch{return false}}
$("connect").onclick=async()=>{const b=$("connect");b.textContent="Connecting…";try{const p=await PathPilotAPI.bootstrapPairing();await PathPilotAPI.setPairingToken(p.pairing_token);await connect();await detect()}finally{b.textContent="Connect PathPilot"}};
async function detect(){tab=await active();const host=new URL(tab?.url||"https://unknown.invalid").hostname;const isFlytBase=/(^|\.)flytbase\.com$/i.test(host);$("site-line").textContent=`You’re on ${friendly(host)}`;$("teach").textContent=isFlytBase?"Teach FlytBase":"Teach this website";$("teach-note").textContent=isFlytBase?"PathPilot will capture only safe, read-only status-review steps in a FlytBase test or sandbox account.":"PathPilot will ask before anything is saved.";if(!(await connect()))return;const {sites}=await PathPilotAPI.listSites();for(const s of sites){const {workflows}=await PathPilotAPI.listWorkflows(s.site_id);if(!workflows.length)continue;const d=await PathPilotAPI.workflowDetail(s.site_id,workflows[0].workflow_id);if(d.site_policy.allowed_domains.includes(host)){site=s;await renderRun(workflows);return;}}site=null;show("teach");}
async function renderRun(workflows){$("website-title").textContent=site.display_name.replace(" (test portal)","");const w=$("workflow");w.innerHTML='<option value="">Select a saved workflow…</option>';for(const x of workflows){const o=document.createElement("option");o.value=x.workflow_id;o.textContent=x.workflow_title.replace(" and prepare a follow-up","");w.append(o);}w.onchange=()=>{$("start").disabled=!w.value;$("start-help").textContent=w.value?"Ready to begin in this visible browser tab.":"Select a saved workflow to begin.";workflow=w.value;};show("run");}
$("teach-another").onclick=()=>show("teach");$("change-site").onclick=()=>show("teach");
$("teach").onclick=async()=>{if(!tab?.url)return;const b=$("teach");const origin=new URL(tab.url).origin+"/*";b.disabled=true;b.textContent="Requesting permission…";try{const granted=await chrome.permissions.request({origins:[origin]});if(!granted){b.disabled=false;b.textContent="Retry permission";$("teach-note").textContent="Permission was not granted. PathPilot cannot access or teach this website until you approve this exact website.";return;}const r=await PathPilotAPI.startTeach(tab.url,$("teach-name").value);b.classList.add("hidden");beginTeaching.classList.remove("hidden");beginTeaching.disabled=false;$("teach-note").textContent=`${r.display_name} connected. Choose Begin teaching conversation to tell PathPilot what to observe.`;}catch(e){b.disabled=false;b.textContent="Retry permission";$("teach-note").textContent="PathPilot could not connect this website. Retry permission.";}};
beginTeaching.onclick=async()=>{beginTeaching.classList.add("hidden");teachChat.classList.remove("hidden");const mode=$("teach-mode").value;teachTyped.classList.toggle("hidden",mode==="voice_voice");teachTalk.classList.toggle("hidden",mode!=="voice_voice");teachBubble(`I’m ready to learn “${$("teach-name").value.trim()||"this workflow"}”.`);convai?.close();convai=new ConvAIClient({getSignedUrl:()=>PathPilotAPI.conversationalSignedUrl(),playAudio:mode!=="text_text",onStatus:t=>$("teach-note").textContent=t,onTranscript:t=>teachBubble(t),onResponse:t=>teachBubble(t),onAudio:()=>$("teach-note").textContent="PathPilot is speaking",onError:()=>teachBubble("Voice connection failed. Please retry."),});try{await convai.connect();if(mode==="voice_voice"){await convai.prepareMic();teachTalk.disabled=false;}convai.sendText(`Hi. Start a teaching conversation for the workflow named ${$("teach-name").value.trim()||"this workflow"}. Give a short spoken greeting and ask for the first safe visible step.`);}catch(e){$("teach-note").textContent="Voice connection failed. Please retry.";teachTalk.disabled=true;}};
$("teach-send").onclick=()=>{const input=$("teach-question"),text=input.value.trim();if(!text)return;input.value="";if(convai)convai.sendText(text);else teachBubble(text);};
$("start").onclick=async()=>{if(!site||!workflow)return;const r=await PathPilotAPI.startSession(site.site_id,workflow,tab.url);sessionId=r.session_id;since=0;$("chat").innerHTML="";$("step").textContent="Step 1 of 5";$("action").textContent="Opening Contacts";bubble("Welcome. I’ll show you how to review a new inbound lead. Ask a question at any time.");show("live");const voiceMode=$("mode").value;convai=new ConvAIClient({getSignedUrl:()=>PathPilotAPI.conversationalSignedUrl(),playAudio:voiceMode!=="text_text",onStatus:t=>$("voice-state").textContent=t,onTranscript:t=>bubble(t,"transcript"),onResponse:t=>bubble(t,"answer"),onAudio:()=>$("voice-state").textContent="PathPilot is speaking",onError:()=>bubble("Voice connection failed. You can still use text.","narration")});try{await convai.connect();if(voiceMode==="voice_voice"){await convai.prepareMic();$("talk").disabled=false;}else $("talk").classList.add("hidden");}catch(e){$("talk").disabled=true;$("voice-state").textContent="Conversation unavailable — use text";}setInterval(poll,1200);};
async function poll(){if(!sessionId)return;const e=await PathPilotAPI.getEvents(sessionId,since);for(const x of e.events){since=Math.max(since,x.id);bubble(x.text,x.event_type==="answer"?"answer":x.event_type==="transcript"?"transcript":"narration");if(x.event_type==="state")$("voice-state").textContent=x.text;}const s=await PathPilotAPI.getSession(sessionId);$("step").textContent=`Step ${s.step_index} of ${s.step_total}`;const live=s.session.status==="in_progress"||s.session.status==="paused";$("talk").disabled=!live||!(convai||stream);$("question").disabled=!live;$("send").disabled=!live;$("pause").disabled=!live; if(!live){$("voice-state").textContent="This walkthrough has ended. Start a new walkthrough to ask PathPilot questions.";$("talk").textContent="Start a walkthrough to ask PathPilot";}}
$("pause").onclick=()=>PathPilotAPI.pauseSession(sessionId);$("stop").onclick=()=>PathPilotAPI.stopSession(sessionId);
$("send").onclick=async()=>{const q=$("question").value.trim();if(!q)return;$("question").value="";$("voice-state").textContent="Checking the current screen";if(convai){try{convai.sendText(q);}catch{bubble("Conversation is reconnecting. Please try again.","narration");}}else await PathPilotAPI.askTextQuestion(sessionId,q,$("mode").value);};
async function mic(){if(stream)return;try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});$("talk").disabled=false}catch{$("talk").disabled=true;}}
async function down(){if(convai){try{convai.startCapture();}catch(e){$("voice-state").textContent="Voice unavailable";}return;}if(!stream||recording)return;recording=true;await PathPilotAPI.interrupt(sessionId);$("voice-state").textContent="Listening";chunks=[];rec=new MediaRecorder(stream,{mimeType:"audio/webm"});rec.ondataavailable=e=>chunks.push(e.data);rec.start();}
async function up(){if(convai){convai.stopCapture();return;}if(!recording)return;recording=false;await new Promise(r=>{rec.onstop=r;rec.stop()});$("voice-state").textContent="Transcribing";await PathPilotAPI.askVoiceQuestion(sessionId,new Blob(chunks,{type:"audio/webm"}),$("mode").value);$("voice-state").textContent="Resuming walkthrough";}
$("talk").onmousedown=down;$("talk").onmouseup=up;$("talk").onmouseleave=up;$("talk").ontouchstart=e=>{e.preventDefault();down()};$("talk").ontouchend=e=>{e.preventDefault();up()};
teachTalk.onmousedown=()=>convai?.startCapture();teachTalk.onmouseup=()=>convai?.stopCapture();teachTalk.onmouseleave=()=>convai?.stopCapture();teachTalk.ontouchstart=e=>{e.preventDefault();convai?.startCapture()};teachTalk.ontouchend=e=>{e.preventDefault();convai?.stopCapture()};
(async()=>{await connect();await detect()})();