import { PathPilotAPI } from "../lib/controller-client.js";
import { ConvAIClient } from "../lib/convai-client.js";
const $=id=>document.getElementById(id); const views={teach:$("teach-view"),run:$("run-view"),live:$("live-view")};
const beginTeaching=$("begin-teaching"),teachChat=$("teach-chat"),teachTyped=$("teach-typed"),teachTalk=$("teach-talk"),teachCapture=$("teach-capture"),captureStep=$("capture-step"),saveWorkflow=$("save-workflow");
const TEACH_ELEMENTS={"begin-teaching":beginTeaching,"teach-chat":teachChat,"teach-typed":teachTyped,"teach-talk":teachTalk,"teach-capture":teachCapture,"capture-step":captureStep,"save-workflow":saveWorkflow};
function missingTeachElements(){return Object.entries(TEACH_ELEMENTS).filter(([,el])=>!el).map(([id])=>id);}
function reportMissingTeachElements(missing){for(const id of missing)console.error(`PathPilot: required teach element #${id} not found in sidepanel.html`);const note=document.getElementById("teach-note");if(note)note.textContent=`PathPilot UI error: missing element(s) ${missing.join(", ")}. Reload the extension in chrome://extensions, then reopen the side panel.`;}
(function checkTeachDom(){const missing=missingTeachElements();if(missing.length){reportMissingTeachElements(missing);const teachBtn=document.getElementById("teach");if(teachBtn)teachBtn.disabled=true;}})();
function teachBubble(text,eventType="narration"){const d=document.createElement("div");d.className="bubble";d.textContent=text;teachChat.append(d);teachChat.scrollTop=teachChat.scrollHeight;if(teachSessionId)PathPilotAPI.logEvent(teachSessionId,eventType,text).catch(()=>{});}
let tab=null,site=null,workflow=null,sessionId=null,since=0,rec=null,chunks=[],stream=null,recording=false,convai=null,capturedWorkflow=null,teachSessionId=null;
function show(name){Object.entries(views).forEach(([k,v])=>v.classList.toggle("hidden",k!==name));}
function bubble(text,type="narration"){const d=document.createElement("div");d.className=`bubble ${type}`;d.textContent=text;$("chat").append(d);$("chat").scrollTop=$("chat").scrollHeight;}
function friendly(host){if(/(^|\.)flytbase\.com$/i.test(host))return "FlytBase";return host.split(".").map(x=>x[0]?.toUpperCase()+x.slice(1)).join(" ");}
async function active(){return new Promise(r=>chrome.runtime.sendMessage({type:"PATHPILOT_GET_ACTIVE_TAB"},r));}
async function connect(){try{const ok=await PathPilotAPI.checkConnection();$("connection").textContent=ok?"Ready":"Not connected";$("connection").className=`status ${ok?"":"off"}`;$("connect").classList.toggle("hidden",ok);return ok}catch{return false}}
$("connect").onclick=async()=>{const b=$("connect");b.textContent="Connecting…";try{const p=await PathPilotAPI.bootstrapPairing();await PathPilotAPI.setPairingToken(p.pairing_token);await connect();await detect()}finally{b.textContent="Connect PathPilot"}};
async function detect(){tab=await active();const host=new URL(tab?.url||"https://unknown.invalid").hostname;const isFlytBase=/(^|\.)flytbase\.com$/i.test(host);$("site-line").textContent=`You’re on ${friendly(host)}`;$("teach").textContent=isFlytBase?"Teach FlytBase":"Teach this website";$("teach-note").textContent=isFlytBase?"PathPilot will capture only safe, read-only status-review steps in a FlytBase test or sandbox account.":"PathPilot will ask before anything is saved.";if(!(await connect()))return;const {sites}=await PathPilotAPI.listSites();for(const s of sites){const {workflows}=await PathPilotAPI.listWorkflows(s.site_id);if(!workflows.length)continue;const d=await PathPilotAPI.workflowDetail(s.site_id,workflows[0].workflow_id);if(d.site_policy.allowed_domains.includes(host)){site=s;await renderRun(workflows);return;}}site=null;show("teach");}
async function renderRun(workflows){$("website-title").textContent=site.display_name.replace(" (test portal)","");const w=$("workflow");w.innerHTML='<option value="">Select a saved workflow…</option>';for(const x of workflows){const o=document.createElement("option");o.value=x.workflow_id;o.textContent=x.workflow_title.replace(" and prepare a follow-up","");w.append(o);}w.onchange=()=>{$("start").disabled=!w.value;$("start-help").textContent=w.value?"Ready to begin in this visible browser tab.":"Select a saved workflow to begin.";workflow=w.value;};if(!workflow&&workflows.length)w.value=workflows[0].workflow_id,w.dispatchEvent(new Event("change"));show("run");}
function isWalkthroughRequest(text){return /\b(give|show|take)\s+me\s+(a\s+)?(the\s+)?(walk\s*-?through|tour|demo)\b|\bwalk\s+me\s+through\b|\bstart\s+(the\s+)?(walk\s*-?through|tour)\b|\bcan\s+you\s+(walk|show)\s+me\b/i.test(text||"");}
let resumeTimer=null;
async function startWalkthrough(){if(!site||!workflow){bubble("There's no saved workflow for this website yet — teach PathPilot one first, then I can walk you through it.","narration");return;}const voiceMode=$("mode").value;$("start").disabled=true;const r=await PathPilotAPI.startSession(site.site_id,workflow,tab.url,voiceMode);sessionId=r.session_id;since=0;$("chat").innerHTML="";$("step").textContent="Step 1";$("action").textContent="Starting…";show("live");wireLiveConvai(voiceMode);setInterval(poll,1200);}
function wireLiveConvai(voiceMode){convai?.close();convai=new ConvAIClient({getSignedUrl:()=>PathPilotAPI.conversationalSignedUrl(),playAudio:voiceMode!=="text_text",onStatus:t=>$("voice-state").textContent=t,onTranscript:t=>{bubble(t,"transcript");if(isWalkthroughRequest(t)){handleWalkthroughIntent(voiceMode);}},onResponse:t=>{bubble(t,"answer");if(resumeTimer)clearTimeout(resumeTimer);resumeTimer=setTimeout(()=>{if(sessionId)PathPilotAPI.resumeSession(sessionId,voiceMode).catch(()=>{});},voiceMode==="voice_voice"?4000:1500);},onAudio:()=>$("voice-state").textContent="PathPilot is speaking",onError:()=>bubble("Voice connection failed. You can still use text.","narration")});convai.connect().then(async()=>{if(voiceMode==="voice_voice"){await convai.prepareMic();$("talk").disabled=false;}else $("talk").classList.add("hidden");}).catch(()=>{$("talk").disabled=true;$("voice-state").textContent="Conversation unavailable — use text";});}
async function handleWalkthroughIntent(voiceMode){if(!sessionId){await startWalkthrough();return;}try{const s=await PathPilotAPI.getSession(sessionId);const status=s.session.status;if(status==="in_progress"){return;}if(status==="paused"){await PathPilotAPI.resumeSession(sessionId,voiceMode||$("mode").value);bubble("Continuing the walkthrough now.","narration");return;}await startWalkthrough();}catch{await startWalkthrough();}}
$("teach-another").onclick=()=>show("teach");$("change-site").onclick=()=>show("teach");
$("teach").onclick=async()=>{if(!tab?.url)return;const b=$("teach");const origin=new URL(tab.url).origin+"/*";b.disabled=true;b.textContent="Requesting permission…";try{const granted=await chrome.permissions.request({origins:[origin]});if(!granted){b.disabled=false;b.textContent="Retry permission";$("teach-note").textContent="Permission was not granted. PathPilot cannot access or teach this website until you approve this exact website.";return;}const r=await PathPilotAPI.startTeach(tab.url,$("teach-name").value);teachSessionId=r.teach_id;b.classList.add("hidden");beginTeaching.classList.remove("hidden");beginTeaching.disabled=false;$("teach-note").textContent=`${r.display_name} connected. Choose Begin teaching conversation to tell PathPilot what to observe.`;}catch(e){b.disabled=false;b.textContent="Retry permission";$("teach-note").textContent="PathPilot could not connect this website. Retry permission.";}};
beginTeaching.onclick=async()=>{const missing=missingTeachElements();if(missing.length){reportMissingTeachElements(missing);return;}beginTeaching.classList.add("hidden");teachChat.classList.remove("hidden");teachCapture.classList.remove("hidden");teachTyped.classList.remove("hidden");const mode=$("teach-mode").value;teachTalk.classList.toggle("hidden",mode!=="voice_voice");teachBubble(`I’m ready to learn “${$("teach-name").value.trim()||"this workflow"}”.`);convai?.close();convai=new ConvAIClient({getSignedUrl:()=>PathPilotAPI.conversationalSignedUrl(),playAudio:mode!=="text_text",onStatus:t=>$("teach-note").textContent=t,onTranscript:t=>{teachBubble(t,"transcript");if(isWalkthroughRequest(t)){handleTeachModeWalkthroughRequest();}},onResponse:t=>teachBubble(t,"answer"),onAudio:()=>$("teach-note").textContent="PathPilot is speaking",onError:()=>teachBubble("Voice connection failed. Please retry."),});try{await convai.connect();if(mode==="voice_voice"){await convai.prepareMic();teachTalk.disabled=false;}convai.sendText(`Hi. Start a teaching conversation for the workflow named ${$("teach-name").value.trim()||"this workflow"}. Give a short spoken greeting and ask for the first safe visible step.`);}catch(e){$("teach-note").textContent="Voice connection failed. Please retry.";teachTalk.disabled=true;}};
async function handleTeachModeWalkthroughRequest(){try{const {sites}=await PathPilotAPI.listSites();for(const s of sites){const {workflows}=await PathPilotAPI.listWorkflows(s.site_id);if(!workflows.length)continue;const d=await PathPilotAPI.workflowDetail(s.site_id,workflows[0].workflow_id);const host=new URL(tab.url).hostname;if(d.site_policy.allowed_domains.includes(host)){site=s;workflow=workflows[0].workflow_id;teachBubble("I have a saved walkthrough for this website — starting it now.","narration");await startWalkthrough();return;}}teachBubble("I don't have a saved walkthrough for this website yet. Demonstrate a safe step here first (Capture safe step, then Review and save), and after that I can walk you through it automatically.","narration");}catch{teachBubble("I couldn't check for a saved walkthrough just now — please try again.","narration");}}
$("teach-send").onclick=()=>{const input=$("teach-question"),text=input.value.trim();if(!text)return;input.value="";if(convai){try{convai.sendText(text);}catch(e){teachBubble("PathPilot voice is not connected yet. Click Begin teaching conversation first.");}}else teachBubble(text);};
captureStep.onclick=async()=>{const link=$("teach-link-text").value.trim();if(!link){$("teach-note").textContent="Name a visible link to demonstrate, exactly as it reads on the page (e.g. VIEW OPENINGS). Menu buttons that only open a dropdown, like Platform, do not count — pick a link that actually navigates.";return;}captureStep.disabled=true;$("teach-note").textContent="Opening a separate, dedicated read-only browser window to safely verify this step. It will close automatically when done — this is expected and does not affect your normal Chrome.";teachBubble(`Opening a separate read-only browser to verify “${link}”…`);try{const r=await PathPilotAPI.captureTeachStep(tab.url,$("teach-name").value.trim()||"Read-only website tour",link);capturedWorkflow={siteId:r.site_id,workflowId:r.workflow_id};teachBubble(`Verified ${r.workflow.steps.length} safe step: ${r.workflow.steps[0].name}. Review and save when ready.`);saveWorkflow.classList.remove("hidden");$("teach-note").textContent="Captured in a dedicated browser, now closed. Nothing has been saved yet.";}catch(e){const reason=e.data?.reason||"PathPilot could not verify that as a safe visible navigation.";teachBubble(`Could not capture “${link}”: ${reason}`);$("teach-note").textContent=reason;}finally{captureStep.disabled=false;}};
saveWorkflow.onclick=async()=>{if(!capturedWorkflow)return;saveWorkflow.disabled=true;$("teach-note").textContent="Saving verified read-only workflow…";try{const r=await PathPilotAPI.saveTeachWorkflow(capturedWorkflow.siteId,capturedWorkflow.workflowId);teachBubble(`Saved “${r.workflow.workflow_title}”. It is now ready to replay as a read-only walkthrough.`);$("teach-note").textContent="Workflow saved. Reopen PathPilot on this website to run it.";}catch(e){$("teach-note").textContent=e.data?.error||"PathPilot could not save this workflow.";}finally{saveWorkflow.disabled=false;}};
$("start").onclick=startWalkthrough;
async function poll(){if(!sessionId)return;const e=await PathPilotAPI.getEvents(sessionId,since);for(const x of e.events){since=Math.max(since,x.id);bubble(x.text,x.event_type==="answer"?"answer":x.event_type==="transcript"?"transcript":"narration");if(x.event_type==="state")$("voice-state").textContent=x.text;}const s=await PathPilotAPI.getSession(sessionId);$("step").textContent=`Step ${s.step_index} of ${s.step_total}`;const browserActive=s.session.status==="in_progress"||s.session.status==="paused";const canAsk=browserActive||!!convai;$("talk").disabled=!canAsk||!(convai||stream);$("question").disabled=!canAsk;$("send").disabled=!canAsk;$("pause").disabled=!browserActive;if(!browserActive&&canAsk&&s.session.status==="completed"){$("action").textContent="Walkthrough finished — still here for questions";}else if(!canAsk){$("voice-state").textContent="This walkthrough has ended. Start a new walkthrough to ask PathPilot questions.";$("talk").textContent="Start a walkthrough to ask PathPilot";}}
$("pause").onclick=()=>PathPilotAPI.pauseSession(sessionId);$("stop").onclick=()=>PathPilotAPI.stopSession(sessionId);
$("send").onclick=async()=>{const q=$("question").value.trim();if(!q)return;$("question").value="";$("voice-state").textContent="Checking the current screen";if(convai){try{if(sessionId)await PathPilotAPI.interrupt(sessionId).catch(()=>{});convai.sendText(q);}catch{bubble("Conversation is reconnecting. Please try again.","narration");}}else await PathPilotAPI.askTextQuestion(sessionId,q,$("mode").value);};
async function mic(){if(stream)return;try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});$("talk").disabled=false}catch{$("talk").disabled=true;}}
async function down(){if(convai){try{if(sessionId)await PathPilotAPI.interrupt(sessionId).catch(()=>{});convai.startCapture();}catch(e){$("voice-state").textContent="Voice unavailable";}return;}if(!stream||recording)return;recording=true;await PathPilotAPI.interrupt(sessionId);$("voice-state").textContent="Listening";chunks=[];rec=new MediaRecorder(stream,{mimeType:"audio/webm"});rec.ondataavailable=e=>chunks.push(e.data);rec.start();}
async function up(){if(convai){convai.stopCapture();return;}if(!recording)return;recording=false;await new Promise(r=>{rec.onstop=r;rec.stop()});$("voice-state").textContent="Transcribing";await PathPilotAPI.askVoiceQuestion(sessionId,new Blob(chunks,{type:"audio/webm"}),$("mode").value);$("voice-state").textContent="Resuming walkthrough";}
$("talk").onmousedown=down;$("talk").onmouseup=up;$("talk").onmouseleave=up;$("talk").ontouchstart=e=>{e.preventDefault();down()};$("talk").ontouchend=e=>{e.preventDefault();up()};
teachTalk.onmousedown=()=>convai?.startCapture();teachTalk.onmouseup=()=>convai?.stopCapture();teachTalk.onmouseleave=()=>convai?.stopCapture();teachTalk.ontouchstart=e=>{e.preventDefault();convai?.startCapture()};teachTalk.ontouchend=e=>{e.preventDefault();convai?.stopCapture()};
(async()=>{await connect();await detect()})();